### ISSUE TITLE
Works with LU935ST

### ISSUE THREAD

**Issue by artificiel** [wilhelmy/benq-remote#1]
Not an issue but more of an FYI: it works with the LU935ST! Thanks for that; it is quite disheartening to see all the people fiddling with serial usb converters to talk to a machine that has an Ethernet interface… Benq should publish these codes.

(heh it is also disheartening that a product sold in 2022 requires flash — but it’s another story).

Note that standby mode has to be switched to network or normal (factory setting is ECO which brings the projector’s network interface down).

**Comment by wilhelmy** [comment]
Honestly, if it has a serial interface you can add wifi support by adding an ESP8266 :)

Not sure why there is no firmware upgrade removing the flash requirement, I'm assuming to upsell you a new model. Life under capitalism :palm_tree:

**Comment by wilhelmy** [comment]
Thank you!
